Repo maintenance
qbicsoftware/sample-notificator-cli pull request #50
Opened 2022-02-03 13:23 UTC by jenniferboedker

Improve readme and githubactions

2022-02-03 13:23 UTC, jenniferboedker commented on .github/CODEOWNER
> +* @qbicsoftware/itss
```suggestion
* @qbicsoftware/itss

```

2022-02-04 09:52 UTC, Steffengreiner requested changes
Nicely done! However there seems to be a copy paste issue with the badge links. Otherwise it looks good!

2022-02-04 09:52 UTC, Steffengreiner commented on README.md
> +[![Build Maven Package](https://github.com/qbicsoftware/sample-notificator-cli/actions/workflows/build_package.yml/badge.svg)](https://github.com/qbicsoftware/spring-boot-rest-service-template/action
```suggestion
[![Build Maven Package](https://github.com/qbicsoftware/sample-notificator-cli/actions/workflows/build_package.yml/badge.svg)](https://github.com/qbicsoftware/sample-notificator-cli/actions/workflows/build_package.yml)
```

2022-02-04 09:52 UTC, Steffengreiner commented on README.md
> +[![Run Maven Tests](https://github.com/qbicsoftware/sample-notificator-cli/actions/workflows/run_tests.yml/badge.svg)](https://github.com/qbicsoftware/spring-boot-rest-service-template/actions/workfl
```suggestion
[![Run Maven Tests](https://github.com/qbicsoftware/sample-notificator-cli/actions/workflows/run_tests.yml/badge.svg)](https://github.com/qbicsoftware/sample-notificator-cli/actions/workflows/run_tests.yml)
```

2022-02-04 09:52 UTC, Steffengreiner commented on README.md
> +[![CodeQL](https://github.com/qbicsoftware/sample-notificator-cli/actions/workflows/codeql-analysis.yml/badge.svg)](https://github.com/qbicsoftware/spring-boot-rest-service-template/actions/workflows
```suggestion
[![CodeQL](https://github.com/qbicsoftware/sample-notificator-cli/actions/workflows/codeql-analysis.yml/badge.svg)](https://github.com/qbicsoftware/sample-notificator-cli/actions/workflows/codeql-analysis.yml)
```

2022-02-04 09:52 UTC, Steffengreiner commented on README.md
> +[![release](https://img.shields.io/github/v/release/qbicsoftware/sample-notificator-cli?include_prereleases)](https://github.com/qbicsoftware/spring-boot-rest-service-template/releases)
```suggestion
[![release](https://img.shields.io/github/v/release/qbicsoftware/sample-notificator-cli?include_prereleases)](https://github.com/qbicsoftware/sample-notificator-cli/releases)
```

2022-02-04 09:52 UTC, Steffengreiner commented on README.md
> +[![license](https://img.shields.io/github/license/qbicsoftware/sample-notificator-cli)](https://github.com/qbicsoftware/spring-boot-rest-service-template/blob/main/LICENSE)
```suggestion
[![license](https://img.shields.io/github/license/qbicsoftware/sample-notificator-cli)](https://github.com/qbicsoftware/sample-notificator-cli/blob/main/LICENSE)
```

2022-02-04 11:12 UTC, KochTobi commented on README.md
> +[![Build Maven Package](https://github.com/qbicsoftware/sample-notificator-cli/actions/workflows/build_package.yml/badge.svg)](https://github.com/qbicsoftware/spring-boot-rest-service-template/action
you can `command` + `R` this easily 😄

2022-02-07 10:23 UTC, Steffengreiner requested changes
Well done! 
Once the PR workflow is gone i'll approve it 👍

2022-02-07 10:41 UTC, Steffengreiner approved these changes
Perfect

2022-02-07 11:30 UTC, merged